### ISSUE TITLE
Cannot compile editor

### ISSUE THREAD

**Issue by iamwilhelm** [witheve/Eve#255]
I've installed the basic dependencies, but looks like typescript couldn't compile the editor.
```
 > bash run.sh 
* Checking dependencies...done.
* Compiling editor...
  x test/include/util.ts(90,15): error TS1005: '>' expected.
```
How do I fix it?

**Comment by joshuafcole** [comment]
Sorry @iamwilhelm, you'll need to use TS 1.6 from the release-1.6 branch to compile master. The reviewed branch still works with TS 1.5 for now.

**Comment by ibdknox** [comment]
As a followup to this you can do:

```
npm install -g typescript@next
```

And it should compile.

**Comment by iamwilhelm** [comment]
That worked. Thanks.
